# schedule_backup.ps1
# Installs a weekly backup task in Windows Task Scheduler.
# ASCII-only, PS 5.1 compatible.
#
# Usage:
#   npm run backup:schedule                   -- install (Sunday 02:00)
#   npm run backup:unschedule                 -- remove
#   .\scripts\schedule_backup.ps1 -Hour 3 -DayOfWeek Monday

param(
    [switch]$Uninstall,
    [ValidateRange(0,23)][int]$Hour = 2,
    [ValidateSet('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday')]
    [string]$DayOfWeek = 'Sunday'
)

$TaskName    = 'AlbumMundial2026-Backup'
$ProjectPath = Split-Path $PSScriptRoot -Parent

# -- Uninstall ----------------------------------------------------------------

if ($Uninstall) {
    Write-Host "Removing task '$TaskName'..."
    try {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction Stop
        Write-Host "Task removed." -ForegroundColor Green
    } catch {
        Write-Warning "Task not found: $($_.Exception.Message)"
    }
    exit 0
}

# -- Validate prerequisites --------------------------------------------------

if (-not (Test-Path (Join-Path $ProjectPath 'package.json'))) {
    Write-Error "package.json not found in: $ProjectPath"
    exit 1
}

$EnvBackupPath = Join-Path $ProjectPath '.env.backup'
if (-not (Test-Path $EnvBackupPath)) {
    Write-Warning ".env.backup not found. Backup task will fail until it is created."
}

# PS 5.1-compatible path detection (no ?. operator)
$NpmCmd   = Get-Command npm  -ErrorAction SilentlyContinue
$NodeCmd  = Get-Command node -ErrorAction SilentlyContinue
$NpmPath  = if ($NpmCmd)  { $NpmCmd.Source  } else { $null }
$NodePath = if ($NodeCmd) { $NodeCmd.Source } else { $null }

if (-not $NpmPath)  { Write-Error "npm not found in PATH.";  exit 1 }
if (-not $NodePath) { Write-Error "node not found in PATH."; exit 1 }

Write-Host "node : $NodePath"
Write-Host "project : $ProjectPath"

# -- Create log directory ----------------------------------------------------

$LogDir  = Join-Path $ProjectPath 'backups'
$LogFile = Join-Path $LogDir 'scheduled_backup.log'
if (-not (Test-Path $LogDir)) { New-Item -ItemType Directory -Path $LogDir -Force | Out-Null }

# -- Write the wrapper script (no heredoc, line by line) ---------------------

$WrapperPath = Join-Path $ProjectPath 'scripts\run_scheduled_backup.ps1'

# Escape single quotes in paths for safe embedding
$SafeProject  = $ProjectPath -replace "'", "''"
$SafeNodePath = $NodePath    -replace "'", "''"

$lines = @(
    "# Auto-generated by schedule_backup.ps1 -- DO NOT EDIT",
    "`$ProjectDir = '$SafeProject'",
    "`$NodeExe    = '$SafeNodePath'",
    "`$LogFile    = Join-Path `$ProjectDir 'backups\scheduled_backup.log'",
    "`$EnvFile    = Join-Path `$ProjectDir '.env.backup'",
    "`$Script     = Join-Path `$ProjectDir 'scripts\backup.mjs'",
    "Set-Location `$ProjectDir",
    "`$Ts = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'",
    "Add-Content -Path `$LogFile -Value `"=== Scheduled backup started: `$Ts ==`"",
    "try {",
    "    `$Out = & `"`$NodeExe`" --env-file=`"`$EnvFile`" `"`$Script`" 2>&1",
    "    `$Code = `$LASTEXITCODE",
    "    Add-Content -Path `$LogFile -Value `$Out",
    "    if (`$Code -eq 0) {",
    "        Add-Content -Path `$LogFile -Value `"=== Backup SUCCEEDED at `$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') ==`"",
    "    } else {",
    "        Add-Content -Path `$LogFile -Value `"=== Backup FAILED (exit `$Code) at `$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') ==`"",
    "    }",
    "} catch {",
    "    Add-Content -Path `$LogFile -Value `"=== Backup ERROR: `$(`$_.Exception.Message) ==`"",
    "}",
    "# Prune: keep last 30 backup dirs",
    "Get-ChildItem (Join-Path `$ProjectDir 'backups') -Directory |",
    "    Sort-Object Name |",
    "    Select-Object -SkipLast 30 |",
    "    ForEach-Object {",
    "        Add-Content -Path `$LogFile -Value `"Pruning: `$(`$_.Name)`"",
    "        Remove-Item `$_.FullName -Recurse -Force",
    "    }"
)

[System.IO.File]::WriteAllLines($WrapperPath, $lines, [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrapper written: $WrapperPath"

# -- Register Task Scheduler task --------------------------------------------

$TriggerTime = '{0:D2}:00' -f $Hour

$Action  = New-ScheduledTaskAction `
    -Execute 'powershell.exe' `
    -Argument "-NonInteractive -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$WrapperPath`"" `
    -WorkingDirectory $ProjectPath

$Trigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek $DayOfWeek -At $TriggerTime

$Settings = New-ScheduledTaskSettingsSet `
    -ExecutionTimeLimit (New-TimeSpan -Hours 1) `
    -StartWhenAvailable `
    -MultipleInstances IgnoreNew

$Principal = New-ScheduledTaskPrincipal `
    -UserId ([System.Security.Principal.WindowsIdentity]::GetCurrent().Name) `
    -LogonType Interactive `
    -RunLevel Limited

Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue

Register-ScheduledTask `
    -TaskName    $TaskName `
    -Action      $Action `
    -Trigger     $Trigger `
    -Settings    $Settings `
    -Principal   $Principal `
    -Description "Weekly backup of Album Mundial 2026 Supabase data." `
    -Force | Out-Null

Write-Host ""
Write-Host "Task registered: $TaskName" -ForegroundColor Green
Write-Host "  Schedule : Every $DayOfWeek at $TriggerTime"
Write-Host "  Log file : $LogFile"
Write-Host "  Run now  : Start-ScheduledTask -TaskName '$TaskName'"
Write-Host "  Uninstall: npm run backup:unschedule"
Write-Host ""
